#!/usr/bin/env bash
# ============================================================
# Project Doctor
# Generated by Venv Batch Template Generator (KeystoneAI) v3.3
# Generated on: 2026-06-04 21:43
# ============================================================
set -uo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="QR_Pro_Suite"
VENV_DIR=".venv"
ENTRY_MODE="file"
APP_ENTRY="src\\main.py"
RUNNER_ARGS=""
PY="$PWD/$VENV_DIR/bin/python"

echo "============================================================"
echo " PROJECT DOCTOR: $PROJECT_NAME"
echo "============================================================"
echo " Project : $PWD"
echo " Mode    : $ENTRY_MODE"
echo " Entry   : $APP_ENTRY"
[[ "$ENTRY_MODE" == "runner" ]] && echo " Args    : $RUNNER_ARGS"
echo ""

if [[ ! -x "$PY" ]]; then
    echo "[FAIL] venv not found: $PY"
    echo "Create it with: python3 -m venv \"$VENV_DIR\""
    exit 1
fi

echo "[OK] venv found: $PY"
echo ""

echo "------------------------------------------------------------"
echo " Python Environment"
echo "------------------------------------------------------------"
"$PY" -c "
import sys
print('Executable :', sys.executable)
print('Version    :', sys.version.split()[0])
print('Prefix     :', sys.prefix)
"
echo ""

echo "------------------------------------------------------------"
echo " pip version"
echo "------------------------------------------------------------"
"$PY" -m pip --version
echo ""

echo "------------------------------------------------------------"
echo " Installed Packages"
echo "------------------------------------------------------------"
"$PY" -m pip list
echo ""

echo "------------------------------------------------------------"
echo " Dependency Health"
echo "------------------------------------------------------------"
"$PY" -m pip check
echo ""

echo "------------------------------------------------------------"
echo " Entry Point Check"
echo "------------------------------------------------------------"
if [[ "$ENTRY_MODE" == "file" ]]; then
    if [[ -f "$APP_ENTRY" ]]; then
        echo "[OK] Entry file found: $APP_ENTRY"
    else
        echo "[FAIL] Entry file NOT found: $APP_ENTRY"
    fi
else
    if "$PY" -c "
import importlib.util, sys
spec = importlib.util.find_spec('$APP_ENTRY')
print(('[OK] Module found: ' if spec else '[FAIL] Module NOT found: ') + '$APP_ENTRY')
sys.exit(0 if spec else 1)
" 2>/dev/null; then
        :
    else
        echo "[FAIL] Module import test failed."
    fi
    [[ "$ENTRY_MODE" == "runner" ]] && echo "[INFO] Runner args: $RUNNER_ARGS"
fi
echo ""

echo "------------------------------------------------------------"
echo " Project Files"
echo "------------------------------------------------------------"
[[ -f "uv.lock" ]]          && echo "[OK]   uv.lock found"
[[ -f "pyproject.toml" ]]   && echo "[OK]   pyproject.toml found"
[[ -f "requirements.txt" ]] && echo "[OK]   requirements.txt found" || echo "[WARN] requirements.txt missing"
echo ""

echo "------------------------------------------------------------"
echo " PyQt6 WebEngine Check"
echo "------------------------------------------------------------"
if "$PY" -c "
from PyQt6 import QtCore
print('PyQt:', QtCore.PYQT_VERSION_STR)
print('Qt  :', QtCore.QT_VERSION_STR)
from PyQt6.QtWebEngineWidgets import QWebEngineView
print('[OK] WebEngine imported successfully.')
" 2>&1; then
    echo "[OK] PyQt6 WebEngine is available."
else
    echo "[FAIL] PyQt6 WebEngine check failed."
    echo "       Run manually:"
    echo "       $PY -c \"from PyQt6.QtWebEngineWidgets import QWebEngineView\""
fi
echo ""

echo "============================================================"
echo " DOCTOR COMPLETE"
echo "============================================================"
