#!/usr/bin/env bash
# ============================================================
# Project-local pip wrapper
# Generated by Venv Batch Template Generator (KeystoneAI) v3.3
# Generated on: 2026-06-04 21:43
#
# Usage:
#   ./pip.sh install requests
#   ./pip.sh install -r requirements.txt
#   ./pip.sh freeze > requirements.txt
#   ./pip.sh list
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

VENV_DIR=".venv"
PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv was not found: $PY"
    echo "        Create it with: python3 -m venv \"$VENV_DIR\""
    exit 1
fi

"$PY" -m pip "$@"
