#!/usr/bin/env bash
# ============================================================
# Project Runner
# Generated by Venv Batch Template Generator (KeystoneAI) v3.3
# Generated on: 2026-06-04 21:43
#
# ENTRY_MODE:
#   file   -> python app.py
#   module -> python -m package.module
#   runner -> python -m runner_module [args...]
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="QR_Pro_Suite"
VENV_DIR=".venv"
ENTRY_MODE="file"
APP_ENTRY="src\\main.py"
RUNNER_ARGS=""

PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv not found: $PY"
    echo ""
    echo "Create it with:"
    echo "    python3 -m venv \"$VENV_DIR\""
    echo "    \"$VENV_DIR/bin/python\" -m pip install --upgrade pip"
    echo "    \"$VENV_DIR/bin/python\" -m pip install -r requirements.txt"
    exit 1
fi

if [[ "$ENTRY_MODE" == "file" && ! -f "$APP_ENTRY" ]]; then
    echo "[ERROR] Entry file not found: $APP_ENTRY"
    echo "Edit run.sh or specify correct entry point."
    exit 1
fi

echo "============================================================"
echo " Running : $PROJECT_NAME"
echo " Project : $PWD"
echo " Python  : $PY"
echo " Mode    : $ENTRY_MODE"
echo " Entry   : $APP_ENTRY"
[[ -n "$RUNNER_ARGS" && "$ENTRY_MODE" == "runner" ]] && echo " Args    : $RUNNER_ARGS"
echo "============================================================"
echo ""

EXITCODE=0

if [[ "$ENTRY_MODE" == "module" ]]; then
    "$PY" -m "$APP_ENTRY" "$@" || EXITCODE=$?
elif [[ "$ENTRY_MODE" == "runner" ]]; then
    if [[ -n "$RUNNER_ARGS" ]]; then
        # shellcheck disable=SC2086
        "$PY" -m "$APP_ENTRY" $RUNNER_ARGS "$@" || EXITCODE=$?
    else
        "$PY" -m "$APP_ENTRY" "$@" || EXITCODE=$?
    fi
else
    "$PY" "$APP_ENTRY" "$@" || EXITCODE=$?
fi

echo ""
echo "============================================================"
echo " Process exited with code: $EXITCODE"
echo "============================================================"
read -r -p "Press Enter to continue..." _
exit $EXITCODE
