#!/usr/bin/env bash
# ============================================================
# Project Setup
# Generated by Venv Batch Template Generator (KeystoneAI) v3.3
# Generated on: 2026-06-04 21:43
#
# Run this once to bootstrap the project environment.
# After setup, use ./run.sh to launch the project.
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="QR_Pro_Suite"
VENV_DIR=".venv"
PY="$PWD/$VENV_DIR/bin/python"

echo "============================================================"
echo " Setting up: $PROJECT_NAME"
echo "============================================================"
echo ""

if ! command -v python3 &>/dev/null; then
    echo "[ERROR] python3 is not installed or not on PATH."
    echo "        Install Python from https://www.python.org/downloads/"
    exit 1
fi

if [[ -x "$PY" ]]; then
    echo "[INFO] Virtual environment already exists at $VENV_DIR/"
    echo "       Delete it first to re-run setup."
    exit 0
fi

echo "[1/3] Creating virtual environment..."
python3 -m venv "$VENV_DIR"
echo ""

echo "[2/3] Upgrading pip..."
"$PY" -m pip install --upgrade pip
echo ""

if [[ -f "requirements.txt" ]]; then
    echo "[3/3] Installing dependencies from requirements.txt..."
    "$PY" -m pip install -r requirements.txt
    echo ""
else
    echo "[3/3] SKIPPED: No requirements.txt found."
    echo "      Add dependencies then run ./sync.sh to install them."
    echo ""
fi

echo "============================================================"
echo " SETUP COMPLETE"
echo " Run ./run.sh to launch the project."
echo "============================================================"
