@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-17 21:46
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=QR_Pro_Suite"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMTcgMjE6NDYNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9UVJfUHJvX1N1aXRl
        echo Ig0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1maWxlIg0Kc2V0ICJBUFBf
        echo RU5UUlk9c3JjXG1haW4ucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCg0Kc2V0ICJQWT0lQ0QlXCVW
        echo RU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAg
        echo ICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8uDQog
        echo ICAgZWNobyBGaXggd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUi
        echo DQogICAgZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSIgLW0gcGlwIGluc3Rh
        echo bGwgLS11cGdyYWRlIHBpcA0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5l
        echo eGUiIC1tIHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KICAgIHBh
        echo dXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgaWYg
        echo bm90IGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBFbnRyeSBmaWxlIG5v
        echo dCBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgIGVjaG8gRWRpdCBydW4uYmF0IG9yIHJ1biB3aXRo
        echo IHRoZSBjb3JyZWN0IGVudHJ5IGZpbGUuDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0K
        echo dGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gUlVOIg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFJ1bm5pbmcgOiAl
        echo UFJPSkVDVF9OQU1FJQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVjaG8gIFB5dGhvbiAgOiAlUFkl
        echo DQplY2hvICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRyeSAgIDogJUFQUF9FTlRS
        echo WSUNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBBcmdzICAgIDogJVJVTk5F
        echo Ul9BUkdTJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT0NCmVjaG8uDQoNCnNldCAiRVhJVENPREU9MCINCg0KaWYgL0kgIiVF
        echo TlRSWV9NT0RFJSI9PSJtb2R1bGUiICgNCiAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgJSoNCikg
        echo ZWxzZSBpZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgKA0KICAgIGlmIGRlZmluZWQgUlVO
        echo TkVSX0FSR1MgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgIVJVTk5FUl9BUkdTISAl
        echo Kg0KICAgICkgZWxzZSAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAlKg0KICAgICkN
        echo CikgZWxzZSAoDQogICAgIiVQWSUiICIlQVBQX0VOVFJZJSIgJSoNCikNCg0Kc2V0ICJFWElUQ09E
        echo RT0hRVJST1JMRVZFTCEiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJvY2VzcyBleGl0ZWQg
        echo d2l0aCBjb2RlOiAhRVhJVENPREUhDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgIUVYSVRDT0RF
        echo IQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMTcgMjE6NDYNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTE3
        echo IDIxOjQ2DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9UVJfUHJvX1N1aXRlIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiQUNUSVZBVEU9
        echo JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNcYWN0aXZhdGUuYmF0Ig0KDQppZiBub3QgZXhpc3QgIiVB
        echo Q1RJVkFURSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMgbm90IGZvdW5kOg0K
        echo ICAgIGVjaG8gICAgICAgICAiJUFDVElWQVRFJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRl
        echo IGl0IHdpdGg6DQogICAgZWNobyAgICAgICAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0K
        echo ICAgIGVjaG8uDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNU
        echo X05BTUUlIC0gVkVOViBTSEVMTCINCmNhbGwgIiVBQ1RJVkFURSUiDQoNCmVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hv
        echo ICBQcm9qZWN0IHNoZWxsIGFjdGl2YXRlZA0KZWNobyAgUHJvamVjdDogIiVDRCUiDQplY2hvICBQ
        echo eXRob24gOg0Kd2hlcmUgcHl0aG9uDQplY2hvICBUeXBlICJleGl0IiB0byBsZWF2ZSB0aGlzIHNo
        echo ZWxsLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT0NCmVjaG8uDQpjbWQgL2sNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0xNyAyMTo0Ng0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1RUl9Qcm9f
        echo U3VpdGUiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2Ny
        echo aXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJP
        echo Ul0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNobyBDcmVh
        echo dGUgaXQgd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQogICAg
        echo cGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gU1lOQyIN
        echo Cg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCmVjaG8gIFN5bmNpbmc6ICVQUk9KRUNUX05BTUUlDQplY2hvICBQeXRob24g
        echo OiAlUFklDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0KZWNobyBbMS8zXSBVcGdyYWRpbmcgcGlwLi4uDQpl
        echo Y2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBpbnN0YWxsIC0tdXBncmFkZSBwaXANCmVjaG8uDQoNCmlm
        echo IGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiAoDQogICAgZWNobyBbMi8zXSBJbnN0YWxsaW5nIGZy
        echo b20gcmVxdWlyZW1lbnRzLnR4dC4uLg0KICAgIGVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQogICAgIiVQWSUiIC1tIHBpcCBp
        echo bnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KKSBlbHNlICgNCiAgICBlY2hv
        echo IFsyLzNdIFNLSVBQRUQ6IE5vIHJlcXVpcmVtZW50cy50eHQgZm91bmQuDQogICAgZWNobyAgICAg
        echo ICBDcmVhdGUgb25lIHdpdGg6IHBpcC5iYXQgZnJlZXplIF4+IHJlcXVpcmVtZW50cy50eHQNCiAg
        echo ICBlY2hvLg0KKQ0KDQplY2hvIFszLzNdIERlcGVuZGVuY3kgaGVhbHRoIGNoZWNrLi4uDQplY2hv
        echo ID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PQ0KIiVQWSUiIC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFNZTkMg
        echo Q09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTE3IDIxOjQ2DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPVFSX1Byb19TdWl0ZSIN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNldCAiQVBQX0VO
        echo VFJZPXNyY1xtYWluLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQpzZXQgIlBZPSVDRCVcJVZFTlZf
        echo RElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQUk9KRUNUIERPQ1RP
        echo UjogJVBST0pFQ1RfTkFNRSUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNobyAg
        echo TW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVBUFBfRU5UUlklDQppZiAv
        echo SSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6ICVSVU5ORVJfQVJHUyUN
        echo CmVjaG8uDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0ZBSUxdIHZlbnYgbm90
        echo IGZvdW5kIGF0OiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRlIGl0IHdpdGg6DQog
        echo ICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAgIHBhdXNlDQogICAgZXhp
        echo dCAvYiAxDQopDQoNCmVjaG8gW09LXSB2ZW52IGZvdW5kOiAiJVBZJSINCmVjaG8uDQoNCmVjaG8g
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tDQplY2hvICBQeXRob24gRW52aXJvbm1lbnQNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImltcG9y
        echo dCBzeXM7IHByaW50KCdFeGVjdXRhYmxlIDonLCBzeXMuZXhlY3V0YWJsZSk7IHByaW50KCdWZXJz
        echo aW9uICAgIDonLCBzeXMudmVyc2lvbi5zcGxpdCgpWzBdKTsgcHJpbnQoJ1ByZWZpeCAgICAgOics
        echo IHN5cy5wcmVmaXgpIg0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIHBpcCB2ZXJzaW9uDQplY2hv
        echo IC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLQ0KIiVQWSUiIC1tIHBpcCAtLXZlcnNpb24NCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBJ
        echo bnN0YWxsZWQgUGFja2FnZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlwIGxpc3QNCmVjaG8uDQoN
        echo CmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tDQplY2hvICBEZXBlbmRlbmN5IEhlYWx0aA0KZWNobyAtLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBw
        echo aXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBFbnRyeSBQb2ludCBDaGVjaw0KZWNo
        echo byAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0NCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgKA0KICAgIGlmIGV4aXN0ICIlQVBQ
        echo X0VOVFJZJSIgKA0KICAgICAgICBlY2hvIFtPS10gRW50cnkgZmlsZSBmb3VuZDogIiVBUFBfRU5U
        echo UlklIg0KICAgICkgZWxzZSAoDQogICAgICAgIGVjaG8gW0ZBSUxdIEVudHJ5IGZpbGUgTk9UIGZv
        echo dW5kOiAiJUFQUF9FTlRSWSUiDQogICAgKQ0KKSBlbHNlICgNCiAgICAiJVBZJSIgLWMgImltcG9y
        echo dCBpbXBvcnRsaWIudXRpbCwgc3lzOyBuYW1lPXInJUFQUF9FTlRSWSUnOyBzcGVjPWltcG9ydGxp
        echo Yi51dGlsLmZpbmRfc3BlYyhuYW1lKTsgcHJpbnQoKCdbT0tdIE1vZHVsZSBmb3VuZDogJyBpZiBz
        echo cGVjIGVsc2UgJ1tGQUlMXSBNb2R1bGUgTk9UIGZvdW5kOiAnKSArIG5hbWUpOyBzeXMuZXhpdCgw
        echo IGlmIHNwZWMgZWxzZSAxKSIgMj5udWwNCiAgICBpZiBlcnJvcmxldmVsIDEgZWNobyBbRkFJTF0g
        echo TW9kdWxlIGltcG9ydCB0ZXN0IGZhaWxlZC4NCiAgICBpZiAvSSAiJUVOVFJZX01PREUlIj09InJ1
        echo bm5lciIgZWNobyBbSU5GT10gUnVubmVyIGFyZ3M6ICIlUlVOTkVSX0FSR1MlIg0KKQ0KZWNoby4N
        echo Cg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0NCmVjaG8gIFByb2plY3QgRmlsZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQppZiBleGlzdCAidXYu
        echo bG9jayIgICAgICAgICAgZWNobyBbT0tdICAgdXYubG9jayBmb3VuZA0KaWYgZXhpc3QgInB5cHJv
        echo amVjdC50b21sIiAgIGVjaG8gW09LXSAgIHB5cHJvamVjdC50b21sIGZvdW5kDQppZiBleGlzdCAi
        echo cmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbT0tdICAgcmVxdWlyZW1lbnRzLnR4dCBmb3VuZA0KaWYg
        echo bm90IGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtXQVJOXSByZXF1aXJlbWVudHMudHh0
        echo IG1pc3NpbmcNCmVjaG8uDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBET0NUT1IgQ09NUExFVEUNCmVjaG8g
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMTcgMjE6NDYNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1RUl9Qcm9fU3VpdGUiDQpzZXQgIlZFTlZfRElS
        echo PS52ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQpp
        echo ZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMgbm90
        echo IGZvdW5kOg0KICAgIGVjaG8gICAgICAgICAiJVBZJSINCiAgICBlY2hvLg0KICAgIHBhdXNlDQog
        echo ICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFRFU1QiDQplY2hvID09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PQ0KZWNobyAgVGVzdGluZzogIiVQUk9KRUNUX05BTUUlIg0KZWNobyAgUHl0aG9uIDogIiVQWSUi
        echo DQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PQ0KZWNoby4NCiIlUFklIiAtbSBweXRlc3QgLXYgJSoNCnNldCAiRVhJVENPREU9
        echo JUVSUk9STEVWRUwlIg0KDQplY2hvLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmlmICIlRVhJVENPREUlIj09IjAiICgN
        echo CiAgICBlY2hvICBURVNUUyBQQVNTRUQNCikgZWxzZSAoDQogICAgZWNobyAgVEVTVFMgRkFJTEVE
        echo ICBeKGV4aXQgY29kZTogJUVYSVRDT0RFJV4pDQopDQplY2hvID09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2Ig
        echo JUVYSVRDT0RFJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
