#!/usr/bin/env bash
# ============================================================
# Project venv shell
# Generated by Venv Batch Template Generator (KeystoneAI) v3.3
# Generated on: 2026-06-04 21:43
#
# Opens an activated shell session for this project.
# Exit with: exit  or  Ctrl-D
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="QR_Pro_Suite"
VENV_DIR=".venv"
ACTIVATE="$PWD/$VENV_DIR/bin/activate"

if [[ ! -f "$ACTIVATE" ]]; then
    echo "[ERROR] Local venv was not found: $ACTIVATE"
    echo "        Create it with: python3 -m venv \"$VENV_DIR\""
    exit 1
fi

echo "============================================================"
echo " Project shell: $PROJECT_NAME"
echo " Project : $PWD"
echo " Activate: $ACTIVATE"
echo " Type 'exit' or Ctrl-D to leave."
echo "============================================================"
echo ""

# Source the activate script in a subshell so the user gets a clean exit
bash --rcfile <(echo "source '$ACTIVATE'; PS1='($PROJECT_NAME) \\u@\\h:\\w\\$ '")
