#!/usr/bin/env bash
# ============================================================
# Dependency Sync (pip)
# Generated by Venv Batch Template Generator (KeystoneAI) v3.3
# Generated on: 2026-06-04 21:43
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="QR_Pro_Suite"
VENV_DIR=".venv"
PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv not found: $PY"
    echo "Create it with: python3 -m venv \"$VENV_DIR\""
    exit 1
fi

echo "============================================================"
echo " Syncing: $PROJECT_NAME"
echo " Python : $PY"
echo "============================================================"
echo ""

echo "[1/3] Upgrading pip..."
"$PY" -m pip install --upgrade pip
echo ""

if [[ -f "requirements.txt" ]]; then
    echo "[2/3] Installing from requirements.txt..."
    "$PY" -m pip install -r requirements.txt
else
    echo "[2/3] SKIPPED: No requirements.txt found."
    echo "      Create one with: ./pip.sh freeze > requirements.txt"
fi
echo ""

echo "[3/3] Dependency health check..."
"$PY" -m pip check
echo ""

echo "============================================================"
echo " SYNC COMPLETE"
echo "============================================================"
